### ISSUE TITLE
QTMConnectLiveLink plugin can't use

### ISSUE THREAD

**Issue by Avelynn** [qualisys/QTM-Connect-For-Unreal#5]
After I finished this  :    Copy the directory .\Prebuilt\Qualisys to C:\Program Files\Epic Games\UE_4.xx\Engine\Plugins.

Plugin "installed" only have  "QTM Connect for Unreal",and don't have "QTMConnectLiveLink" .

**Comment by mlveggo** [comment]
Does it appear in the LiveLink plugin as a LiveLink source?
Did you enable the LiveLink plugin?

**Comment by mlveggo** [comment]
Here are some of our tutorials for using our Unreal plugin
https://www.youtube.com/watch?v=lJ3CwEu2OxY
https://www.youtube.com/watch?v=YZ24RH2_LZM
https://www.youtube.com/watch?v=IC70NnnBw60

**Comment by mlveggo** [comment]
Are you using UE 4.21?
We haven't yet published prebuilt plugins for UE4.22.

**Comment by Avelynn** [comment]
No，the QTMConnectLiveLink plugin didn't appear.  
(Thank you very much for your reply!)

And,I'm using UE4.21.2.

**Comment by mlveggo** [comment]
Have you enabled Unreals LiveLink plugin?

**Comment by Avelynn** [comment]
No,I didn't enabled it.And,It's UE_4.21.




------------------ 原始邮件 ------------------
发件人: "Morgan Larsson"<notifications@github.com>;
发送时间: 2019年4月17日(星期三) 下午4:24
收件人: "qualisys/QTM-Connect-For-Unreal"<QTM-Connect-For-Unreal@noreply.github.com>;
抄送: "🌸"<964878752@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [qualisys/QTM-Connect-For-Unreal] QTMConnectLiveLink plugin can'tuse (#5)




Have you enabled Unreals LiveLink plugin?

**Comment by Avelynn** [comment]
Did you see the picture I sent you?


I don't know if it was sent successfully.





------------------ 原始邮件 ------------------
发件人: "Morgan Larsson"<notifications@github.com>;
发送时间: 2019年4月17日(星期三) 下午4:24
收件人: "qualisys/QTM-Connect-For-Unreal"<QTM-Connect-For-Unreal@noreply.github.com>;
抄送: "🌸"<964878752@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [qualisys/QTM-Connect-For-Unreal] QTMConnectLiveLink plugin can'tuse (#5)




Have you enabled Unreals LiveLink plugin?

**Comment by Avelynn** [comment]
Now,if I open QualisysAvatar project,there will be some errors.



------------------ 原始邮件 ------------------
发件人: "Morgan Larsson"<notifications@github.com>;
发送时间: 2019年4月17日(星期三) 下午4:22
收件人: "qualisys/QTM-Connect-For-Unreal"<QTM-Connect-For-Unreal@noreply.github.com>;
抄送: "🌸"<964878752@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [qualisys/QTM-Connect-For-Unreal] QTMConnectLiveLink plugin can'tuse (#5)




Are you using UE 4.21?
 We haven't yet published prebuilt plugins for UE4.22.

**Comment by Avelynn** [comment]
I've seen your tutorial,but the plugin cannot be imported into my UE4.

**Comment by Avelynn** [comment]
The problem has been solved ! I was so stupid ! It appear in the LiveLink plugin as a LiveLink source.

**Comment by Avelynn** [comment]
Now ,the QTM Connect for Unreal and the QTMConnectLiveLink and Unreals LiveLink plugin can't be enabled. If I enable them and restart UE4 , the project will can't be opened.

**Comment by mlveggo** [comment]
Resolved in another support thread

**Comment by Avelynn** [comment]
Thank you so much！

**Comment by Avelynn** [comment]
[Ques1.docx](https://github.com/qualisys/QTM-Connect-For-Unreal/files/3220065/Ques1.docx)

**Comment by Avelynn** [comment]
Sorry to bother you again. I don't know what the problem is, but the project still can't be opened.
